### ISSUE TITLE
Can`t resolve #app in a nuxt project since v3.1.1

### ISSUE THREAD

**Issue by apss-pohl** [import-js/eslint-import-resolver-typescript#120]
Sorry i haven't had much time the last days. Here is a repoduction:

https://codesandbox.io/s/nuxt3-eslint-import-4ytvs8?file=/apps/nuxt/src/app.vue
Would you mind to reopen the other issue (https://github.com/import-js/eslint-import-resolver-typescript/issues/117) and delete this one?

**Comment by JounQin** [comment]
> Would you mind to reopen the other issue (https://github.com/import-js/eslint-import-resolver-typescript/issues/117) and delete this one?

What the difference to keep this one? There is no reproduction in the original issue, that's why it is closed.

---

Thanks for the reproduction, but I don't know how to run the script in codesandbox, can you provide a GitHub repository instead? Export the codesandbox app into a repository for example.

**Comment by apss-pohl** [comment]
Let me check how to export. In the meantime: 
You can open a console following the red arrows and run "yarn lint" to reproduce. If you change back to 2.7 the error disappears.
![image](https://user-images.githubusercontent.com/95089598/176842385-3197e566-a120-44d1-b7b5-cfe0d36ab1f8.png)

**Comment by apss-pohl** [comment]
Here you are: https://github.com/apss-pohl/nuxt3-eslint-import2

**Comment by JounQin** [comment]
> Here you are: [apss-pohl/nuxt3-eslint-import2](https://github.com/apss-pohl/nuxt3-eslint-import2)

Thanks then, I'll take a look when I'm free.

You can also help to debug if you want to contribute.

**Comment by JounQin** [comment]
Where have you `#app` defined?

**Comment by apss-pohl** [comment]
> Where have you `#app` defined?

If is created once you run yarn dev or similar. It will create a folder .nuxt containing the required tsconfig.json:
![image](https://user-images.githubusercontent.com/95089598/176844198-c87ba722-1d24-436e-9c0f-0c5cd79f713d.png)

**Comment by JounQin** [comment]
```log
gitpod /workspace/nuxt3-eslint-import2 (main) $ yarn dev
yarn run v1.22.19
$ yarn nuxt nuxi dev
$ /workspace/nuxt3-eslint-import2/node_modules/.bin/nuxt nuxi dev
Nuxt CLI v3.0.0-rc.4-27609974.fe508f5                                                                                                                                                07:19:43
                                                                                                                                                                                     07:19:43
Invalid command nuxi
Usage: npx nuxi dev|build|preview|start|analyze|generate|prepare|typecheck|usage|info|init|create|upgrade|test|add|new [args]                                                        07:19:43

Use npx nuxi [command] --help to see help for each command                                                                                                                           07:19:43

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm just getting more and more confused, please provide reproduce steps...

**Comment by JounQin** [comment]
```log
gitpod /workspace/nuxt3-eslint-import2 (main) $ yarn dev
yarn run v1.22.19
$ yarn nuxt nuxi dev
$ /workspace/nuxt3-eslint-import2/node_modules/.bin/nuxt nuxi dev
Nuxt CLI v3.0.0-rc.4-27609974.fe508f5                                                                                                                                                07:19:43
                                                                                                                                                                                     07:19:43
Invalid command nuxi
Usage: npx nuxi dev|build|preview|start|analyze|generate|prepare|typecheck|usage|info|init|create|upgrade|test|add|new [args]                                                        07:19:43

Use npx nuxi [command] --help to see help for each command                                                                                                                           07:19:43

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm just getting more and more confused, please provide reproduce steps...

**Comment by apss-pohl** [comment]
Assumed it would work ootb from codesandbox. I fixed the build, should be good to go now.

**Comment by JounQin** [comment]
Thanks, just found the bug, working on a fix.

**Comment by apss-pohl** [comment]
Awesome, thank you so much!

**Comment by JounQin** [comment]
@apss-pohl Please try

```sh
# yarn 1
yarn add https://pkg.csb.dev/import-js/eslint-import-resolver-typescript/commit/16d9e762/eslint-import-resolver-typescript
# yarn 2, 3
yarn add eslint-import-resolver-typescript@https://pkg.csb.dev/import-js/eslint-import-resolver-typescript/commit/16d9e762/eslint-import-resolver-typescript/_pkg.tgz
# npm
npm i https://pkg.csb.dev/import-js/eslint-import-resolver-typescript/commit/16d9e762/eslint-import-resolver-typescript
```

I confirm it is working on your reproduction.

**Comment by apss-pohl** [comment]
Works like a charm on my other project!

**Comment by JounQin** [comment]
@apss-pohl 

`eslint-import-resolver-typescript@3.1.3` has been released.

And thanks for the reproduction again, it saves both of our time.
