### ISSUE TITLE
Paths to direct file not resolved

### ISSUE THREAD

**Issue by kekel87** [import-js/eslint-import-resolver-typescript#125]
Hello,

I am updating my Angular project and its dependencies.

`eslint-import-resolver-typescript@3.1.4` is not able to resolve aliases to direct file versions anymore.

`app.module.ts`
```typescript
import { HeaderModule } from '~app/core/header/header.module'; // This work
import { environment } from '~environment'; // This doesn't work anymore.
```

`tsconfig.json`
```json
   "paths": {
      "~environment": ["src/environments/environment"], // Alias to `src/environments/environment.ts` file
      "~shared/*": ["src/app/shared/*" ],
      "~app/*": ["src/app/*" ],
      "~mocks/*": ["src/tests/mocks/*"]
    }
```

Output:
```
...\angular-seed\src\app\app.module.ts
  11:29  error  Unable to resolve path to module '~environment'  import/no-unresolved

✖ 1 problem (1 error, 0 warnings)
```

I rolback my version to `^2.7.0` et ça fonctionne.

**Comment by JounQin** [comment]
A reproduction is required.

**Comment by kekel87** [comment]
Here is an example of reproduction:

https://github.com/kekel87/angular-seed/tree/eslint-import-resolver-typescript-issue-125

Step to reproduce:
```
npm i
npm run lint
```

**Comment by JounQin** [comment]
@kekel87 

`eslint-import-resolver-typescript@3.1.5` has been released.

And thanks for the reproduction again, it saves both of our time.

---

If you found my projects useful, please consider donating such as a cup of coffee, thanks.
