### ISSUE TITLE
Unable to resolve modules when using yarn's PnP linker

### ISSUE THREAD

**Issue by meriouma** [import-js/eslint-import-resolver-typescript#130]
This is a breaking change in v3. Trying to run eslint with `eslint-import-resolver-typescript@3+` yields multiple
`error  Resolve error: File '@equisoft/typescript-config/tsconfig.standards.json' not found.`
`4:15  error  Unable to resolve path to module './some-module`

Reproduction branch : https://github.com/kronostechnologies/tax-ca/tree/get-tsconfig-issue
Steps :
- `yarn install`
- `yarn eslint`

I believe the issue is caused by the change from tsconfig-paths to get-tsconfig (https://github.com/privatenumber/get-tsconfig/issues/26)

**Comment by JounQin** [comment]
If you already know it's an issue from `get-tsconfig`, then you don't need to raise this issue?

**Comment by meriouma** [comment]
To document this package doesn't work anymore when using yarn PnP?

**Comment by JounQin** [comment]
I depends on `get-tsconfig`, and you can help to support that.

And I've document `use get-tsconfig to replace tsconfig-paths` in v3, and that's why it is a major version.

**Comment by JounQin** [comment]
I noticed you raised https://github.com/privatenumber/get-tsconfig/pull/27, but you just gave up by closing the PR.

Personally I don't use yarn pnp, you need provide a reproduction for `get-tsconfig`, so that it helps and saves all of our time.

By the mean time, you can still use v2 as workaround for now.

**Comment by JounQin** [comment]
https://github.com/import-js/eslint-import-resolver-typescript/pull/133

After digging, I found it still should be fixed in `get-tsconfig` because we have no access to `extends` field in `tsconfig.json`.

@meriouma If you are going to fix that issue, I'll just leave it as-is, or I might work on a fix for `get-tsconfig` instead.

**Comment by JounQin** [comment]
@meriouma `eslint-import-resolver-typescript@3.2.2` has been released with PnP support!

**Comment by meriouma** [comment]
Wow, thanks @JounQin for the fast work. although it is causing more issue. Now there are a lot of import error appearing :
```
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-extraneous-dependencies
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-unresolved
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-duplicates
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/order
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-self-import
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-cycle
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-useless-path-segments
1:1   error  Resolve error: typescript with invalid interface loaded as resolver  import/no-relative-packages
1:1  error  Unable to resolve path to module './annotators/annotator'            import/no-unresolved
2:27  error  Unable to resolve path to module './converters/converter'            import/no-unresolved
3:28  error  Unable to resolve path to module './model/issue'                     import/no-unresolved
4:24  error  Unable to resolve path to module './model/report'                    import/no-unresolved
5:68  error  Unable to resolve path to module './report-filters'                  import/no-unresolved
6:30 error  Unable to resolve path to module './report-reader'                   import/no-unresolved
```

I took a look at your PR and I'm not sure what is the change that could cause this issue 🤔

**Comment by JounQin** [comment]
@meriouma See #135, working on a fix.

**Comment by meriouma** [comment]
Oh, right. Thank you!

**Comment by acusti** [comment]
for anyone else like myself who encountered a similar thing to @meriouma and then found this issue about it, i needed to add `'import/external-module-folders': ['.yarn'],` to my `settings` to get this to work ([details here](https://acusti.ca/blog/2025/01/13/eslint-plugin-import-with-yarn-pnp/)). so my full `settings` object in my `eslint.config.js` file looks like:
```js
    settings: {
        'import/resolver': { typescript: { alwaysTryTypes: true } },
        'import/external-module-folders': ['.yarn'],
    },
```
