### ISSUE TITLE
3.2.2 doesn't include project files

### ISSUE THREAD

**Issue by jyeros** [import-js/eslint-import-resolver-typescript#135]
v3.2.2 doesn't include project files
![image](https://user-images.githubusercontent.com/43852295/177404224-bbb02abe-e4c6-4752-b96b-7f2a8fbdfa2b.png)

These are the only 3 files:
![image](https://user-images.githubusercontent.com/43852295/177404351-aef7c780-b7e5-44f9-a228-c1d0e9167f72.png)

**Comment by ixuz** [comment]
Transition from version `3.2.1` to `3.2.2` caused our CI pipeline to fail.
Errors like these appear in the eslint log:

```
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/namespace
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/no-unresolved
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/default
   1:1   warning  Resolve error: typescript with invalid interface loaded as resolver  import/no-duplicates
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/no-extraneous-dependencies
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/order
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/no-self-import
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/no-cycle
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/no-relative-packages
   1:1   warning  Resolve error: typescript with invalid interface loaded as resolver  import/no-named-as-default
   1:1   warning  Resolve error: typescript with invalid interface loaded as resolver  import/no-named-as-default-member
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/extensions
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/no-useless-path-segments
   1:1   error    Resolve error: typescript with invalid interface loaded as resolver  import/named
```

**Comment by minddust** [comment]
+1

**Comment by amikheychik** [comment]
There is a regression from `3.2.1` to `3.2.2` and relative paths are not resolved now.

**Comment by JounQin** [comment]
I'm sorry for this accident, I'll check ASAP.

**Comment by JounQin** [comment]
@jyeros @kristinlindquist @hori-ryota @melink14 @cherryblossom000 @minddust @meriouma @alecthw

`eslint-import-resolver-typescript@3.2.4` has been released with correct contents.

---

If you found my projects useful, please consider donating such as a cup of coffee, thanks.

**Comment by Lonli-Lokli** [comment]
I am not sure yet what is the reason, but my import/order stopped working when I switched to Yarn PnP - it does not treat projects starting with `@cv` as internal, with this configuration

```
"import/order": [
          "error",
          {
            "groups": [["builtin", "external"], "internal", ["parent", "sibling", "index"]],
            "pathGroups": [
              {
                "pattern": "@cv/**",
                "group": "internal"
              }
            ],
            "pathGroupsExcludedImportTypes": ["builtin"],
            "newlines-between": "always",
            "warnOnUnassignedImports": true,
            "alphabetize": {
              "order": "asc",
              "caseInsensitive": true
            }
          }
        ],
```

**Comment by JounQin** [comment]
@Lonli-Lokli https://antfu.me/posts/why-reproductions-are-required

**Comment by Lonli-Lokli** [comment]
@JounQin how small should be reproduction? Because now I already have my project with that, and Yarn PnP was not a small task

**Comment by JounQin** [comment]
> @JounQin how small should be reproduction? Because now I already have my project with that, and Yarn PnP was not a small task

You issue seems not related to project size, so just a reproduction is needed, no matter its size.
