### ISSUE TITLE
Absolute imports / aliases in monorepos

### ISSUE THREAD

**Issue by toerndev** [import-js/eslint-import-resolver-typescript#148]
The README shows several ways to specify multiple projects in monorepos, which is great.

What if each monorepo package enables absolute imports by resolving from `./src`, and several projects have the same subpaths, e.g. `src/utils`. If I'm reading the source correctly, this resolver will always return the first match. I seemed to get unpredictable results, where these absolute imports were resolved differently depending on the working directory.

To circumvent this, I tried to only set `settings['import/resolver'].typescript.project` to the local project/package in an override for each project. Maybe that's the solution? But I fell down this weird rabbit hole of obscure errors, so I'm wondering if there is a recommendation for this scenario.

**Comment by JounQin** [comment]
PR welcome.

**Comment by toerndev** [comment]
The reason I ask here is to understand whether this sounds like an actual problem or not from the perspective of this library.

With custom cross-package type resolution inside a linter plugin, it gets abstract enough that it's hard for me to understand what's even supposed to work. :-)

I'll close this for now to keep the issue tracker clean.
