### ISSUE TITLE
import/resolver with rules from import/errors and using @typescript-esint/parser causes VSCode to hang while saving files

### ISSUE THREAD

**Issue by lachlanhunt** [import-js/eslint-import-resolver-typescript#163]
Given this .eslintrc.js

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['import'],
  rules: {
    'import/no-unresolved': 2, // Enabling one or more of these 3 rules causes the issue.
    // 'import/named': 2,
    // 'import/namespace': 2,
  },
  settings: {
    'import/resolver': {
      typescript: {},
    },
  },
};
```

Then with with the [ESLint extension](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) for VSCode installed, and enabling this option in VSCode's settings.json

```json
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
```

This causes VSCode to get stuck while trying to save, showing a dialog saying "Getting code actions from ESLint ...".

I have tried to diagnose this issue by following the advice in microsoft/vscode-eslint#1344, but I've only been able to narrow it down to this combination of settings. I don't actually know for sure if the bug is somewhere in these 3 rules, in typescript's parser or the ESLint plugin, or even somewhere else. But I've only had this issue occur with either of those 3 specific rules enabled.

I've only been able to workaround this by disabling the 3 rules: `import/no-unresolved`, `import/named` and `import/namespace`.

**Comment by JounQin** [comment]
I don't understand why the issue is created here, this resolver has nothing to do with the editor, why you think this is caused by this resolver instead of the plugin or vscode-eslint extension, or even VSCode itself?

**Comment by vire** [comment]
Sadly I can only confirm that disabling `import/no-unresolved`, `import/named` and `import/namespace` did NOT resolve the "Getting code actions from ESLint ...". problem.

**Comment by JounQin** [comment]
> Sadly I can only confirm that disabling `import/no-unresolved`, `import/named` and `import/namespace` did NOT resolve the "Getting code actions from ESLint ...". problem.

So there is nothing related to this resolver.

**Comment by lachlanhunt** [comment]
I opened it here because I mistakenly thought this was the repo for the import plugin. Both are within import-js and I didn't notice, so that was my mistake. I did intend to open it in import-js/eslint-plugin-import.

But also, in that microsoft/vscode-eslint#1344 issue I linked to, it very clearly explained that issues like this are more likely caused by slow eslint plugins, rather than VSCode or the extension itself.

Would you prefer I reopen the issue within in import-js/eslint-plugin-import?

**Comment by JounQin** [comment]
@lachlanhunt I think there are already issues for performance problems, see https://github.com/import-js/eslint-plugin-import/issues?q=performance+
