### ISSUE TITLE
`no-cycle` not working with import resolver 

### ISSUE THREAD

**Issue by hackwaly** [import-js/eslint-import-resolver-typescript#180]
https://github.com/import-js/eslint-plugin-import/issues/2468

**Comment by JounQin** [comment]
Please provide a minimal but runnable reproduction.

**Comment by hackwaly** [comment]
I can confirm in my real project it reproduces. I can't make it reproduce in a simple ts project. I shall reopen it when I found how to make a reproduction.

**Comment by JounQin** [comment]
@hackwaly Or maybe you can first try `DEBUG=eslint-import-resolver-typescript eslint FILENANE` for debugging on your real project.
