### ISSUE TITLE
question: resolution order of `project`

### ISSUE THREAD

**Issue by jjangga0214** [import-js/eslint-import-resolver-typescript#184]
Hi!
For example, in this case, which one would be resolved, a or b?

```js
'import/resolver': {
  typescript: {
    // ...
    project: [
      'tsconfig.a.json',
      'tsconfig.b.json',
    ]
  },
}
```
Thanks :)

**Comment by JounQin** [comment]
They will be tried in sequence, so `tsconfig.a.json` will be tried first, if no result resolved, `tsconfig.b.json` will be tried.

See also https://github.com/import-js/eslint-import-resolver-typescript/issues/87#issuecomment-998406411
