### ISSUE TITLE
iconv-lite not found in imported namespace

### ISSUE THREAD

**Issue by lublak** [import-js/eslint-import-resolver-typescript#186]
If it is the same problem as this one it can be closed immediately:  https://github.com/import-js/eslint-import-resolver-typescript/issues/31

Only solution: disable import/namespace

I would like to use this library.
I use iconv-lite following:

```ts
import * as iconv from 'iconv-lite';

iconv.encodingExists('utf8') // error 'encodingExists' not found in imported namespace 'iconv' import/namespace
iconv.decode(buffer, decoding); // error 'decode' not found in imported namespace 'iconv' import/namespace
iconv.encode(text, encoding); // error 'encode' not found in imported namespace 'iconv' import/namespace
```

**Comment by JounQin** [comment]
There is no need to use `declare module 'iconv-lite'` in its self declaration package.

**Comment by JounQin** [comment]
See also https://github.com/wojtekmaj/react-date-picker/pull/419

**Comment by lublak** [comment]
@JounQin thanks. I created a pull request for this.

**Comment by lublak** [comment]
@JounQin is it possible to override this file in my own project?
I don't expect it to be released in the next few months.
And of course, since I don't want to wait that long, I would need a solution now.

**Comment by JounQin** [comment]
@lublak You can try https://github.com/ds300/patch-package

**Comment by lublak** [comment]
@JounQin thanks :) not the best solution, but I think the only one that exists. Typescript does not support overwriting if I see correctly. So no /myowntypingsfolder/
