### ISSUE TITLE
declare module and import/no-unresolved

### ISSUE THREAD

**Issue by nathanhannig** [import-js/eslint-import-resolver-typescript#197]
I am using the module '@types/arcgis-js-api' which uses declare module

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/arcgis-js-api/v3/index.d.ts

`import Portal from "esri/arcgis/Portal";`

When using eslint-plugin-import with eslint-import-resolver-typescript I get 
`error  Unable to resolve path to module 'esri/arcgis/Portal'  import/no-unresolved`

How can I set up to resolve this properly?

**Comment by Pixcell** [comment]
No update on this?
I'm facing the same issue with the $env/static/public module defined by sveltekit

**Comment by linonetwo** [comment]
I have a `declare module` for tiddlywiki

```ts
declare module '$:/core/modules/widgets/widget.js' {
  import { Widget } from 'tiddlywiki';
  export { Widget as widget };
}
```

And use it like `import { widget as Widget } from '$:/core/modules/widgets/widget.js';`

Now I have to use `'import/no-unresolved': [2, { ignore: ['\\$:/'] }],` to ignore it.

**Comment by linonetwo** [comment]
Shit, I have encountered this before! Wasting time dealing with this every time.

**Comment by JounQin** [comment]
It seems `.d.ts` is resolved correctly, but `eslint-plugin-import` doesn't understand `declare module` statement, so this is similar to https://github.com/import-js/eslint-plugin-import/issues/1479 what means this does not belong to this resolver.
