### ISSUE TITLE
Consider removing `eslint-plugin-import` from `peerDependencies`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [import-js/eslint-import-resolver-typescript#203]
As far as I can tell, it isn't actually needed for this package to run, and, as the README says, `eslint-plugin-i` is an alternative.
It's not really a big deal, but getting a warning about not having `eslint-plugin-import` installed (or having it auto-installed but never used in some setups) is a less-than-ideal experience.

**Comment by JounQin** [comment]
`eslint-plugin-i` needs to be installed as `eslint-plugin-import@npm:eslint-plugin-i`, there will be a `eslint-plugin-import` folder in `node_modules`.

We don't guarantee without `eslint-plugin-import` installed.

Or do you have any valid use case?
