### ISSUE TITLE
Types from import modules are `any`

### ISSUE THREAD

**Issue by Ridermansb** [import-js/eslint-import-resolver-typescript#216]
With basic config

```
    "import/parsers": {
      "@typescript-eslint/parser": [".ts", ".tsx"]
    },
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true,
        "project": ["./packages/*/tsconfig.json", "./tsconfig.json"]
      }
    }
  },
```
> Notice that I'm using monorepo with npm workspaces

![image](https://user-images.githubusercontent.com/725337/224516818-ba5f3818-8551-4929-8c97-3b1638131e5b.png)

----------

if I use relative path, works!

**Comment by JounQin** [comment]
Not related to this resolver
