### ISSUE TITLE
Resolver option cache doesn't take into account process.cwd()

### ISSUE THREAD

**Issue by kingston** [import-js/eslint-import-resolver-typescript#217]
In version 3.5.0 of the plugin, the comparison for the cached resolver options was updated to use the object hash instead of referential equality. However, this led to a subtle bug with monorepo setups in VSCode where the import resolver would cache the path map from one project for all projects resulting in continual errors for all other projects.

I went into the rabbit hole and figured out that it was because the `initMappers` function relies on `process.cwd()`: https://github.com/import-js/eslint-import-resolver-typescript/blob/d8dd3ca74026dd40993c7e758179b40909ff216c/src/index.ts#L335
However, the logic for checking whether to initMappers only check options: https://github.com/import-js/eslint-import-resolver-typescript/blob/d8dd3ca74026dd40993c7e758179b40909ff216c/src/index.ts#L326) and does not check if `process.cwd()` has changed as well. Therefore, the cache for mappers is never updated resulting in an error when the `process.cwd()` is changed. This is something that the VSCode ESLint plugin does to support multiple working directories (https://github.com/microsoft/vscode-eslint/blob/560df864580a9381d84b2f1e408f46f6600fda48/server/src/eslint.ts#L1056).

It seems a simple solution is to also check if process.cwd() has changed in initMappers. I can put together a quick PR for that if it seems like a reasonable solution.

**Comment by lsmurray** [comment]
@kingston I submitted a PR. linked above. I didn't do a deep dive into the code but if you want to double check that it does what you would expect that would be helpful. It's only two lines. Trying to push this through.

**Comment by kingston** [comment]
> @kingston I submitted a PR. linked above. I didn't do a deep dive into the code but if you want to double check that it does what you would expect that would be helpful. It's only two lines. Trying to push this through. If it doesn't match what you would expect. Feel free to comment and I'll fix it up, or you can submit your own and I'll close mine out.

Oh awesome - looks great. Thank you!
