### ISSUE TITLE
Question: how to map ".tsx" fiels to import ending with ".js" extension?

### ISSUE THREAD

**Issue by giacomorebonato** [import-js/eslint-import-resolver-typescript#234]
Hi, thank you a lot for this plugin.

I am working on a TypeScript project with React and ESM (I have `"type": "module"` in package.json).
In my `tsconfig.json` I have `"jsx": "react-jsx",`, hence all my `*.tsx` files get compiled to `.js`.

Eslint returns this error in the import and goes away if I use the `.jsx` extension.

<img width="713" alt="Screenshot 2023-08-08 at 15 15 24" src="https://github.com/import-js/eslint-import-resolver-typescript/assets/630796/8a828ced-c8ee-4396-ab26-836eecc99fa9">

This is how my settings section looks like:

```js
    'import/parsers': {
      '@typescript-eslint/parser': ['.ts', '.tsx'],
    },
    'import/resolver': {
      node: {
        extensions: ['.js', '.jsx'],
      },
      typescript: {
        project: 'tsconfig.json',
      },
    }
```

What should I change to have `tsx` files mapped to import ending with `.js` extension?

**Comment by JounQin** [comment]
https://github.com/import-js/eslint-import-resolver-typescript/blob/71b23a206514842fef70a99220e5ffb1d6da2a0e/src/index.ts#L61

There do have such a alias, so please provide a runnable reproduction.

**Comment by giacomorebonato** [comment]
Sorry, it's in a private repository. I'll re-open once can I provide a runnable reproduction.

**Comment by cvle** [comment]
Running into the same problem when the import is through the tsconfig `paths` mapping
