### ISSUE TITLE
import/no-useless-path-segments doesn't work on absolute imports

### ISSUE THREAD

**Issue by icatalina** [import-js/eslint-import-resolver-typescript#237]
When using an absolute import `import/no-useless-path-segments` is ignored:

## Absolute import:
<img width="410" alt="image" src="https://github.com/import-js/eslint-import-resolver-typescript/assets/4542735/79585bf2-fef6-4bbe-8557-03905b6af7d2">

## Relative import:
<img width="345" alt="image" src="https://github.com/import-js/eslint-import-resolver-typescript/assets/4542735/6e364622-78a6-48bc-9479-db2debdeae00">

**Comment by JounQin** [comment]
I believe it's not a resolve's issue?

**Comment by icatalina** [comment]
oh, sorry, I guess this goes into the import/export, my bad 🤦 

Moved: 
- https://github.com/import-js/eslint-plugin-import/issues/2865
