### ISSUE TITLE
Cannot use with `eslint-plugin-i`

### ISSUE THREAD

**Issue by csantos1113** [import-js/eslint-import-resolver-typescript#253]
I always want "faster speed" and was hyped when I saw this in your README.md

> This plugin adds [TypeScript](https://www.typescriptlang.org/) support to [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) (**Or maybe you want to try [eslint-plugin-i](https://github.com/un-es/eslint-plugin-i) for faster speed**)

But I was pulled down of my excitement because there is a required peerDependency for `eslint-plugin-import` that doesn't let me swap 😞 

https://github.com/import-js/eslint-import-resolver-typescript/blob/340054d3afb8b31f5ade6192095b644e9c299fcb/package.json#L66

Would it be possible to make these 2 optional peerDependencies instead? 🙏

**Comment by JounQin** [comment]
It's clearly documented that you should use alias on installation.

```sh
npm install -D eslint-plugin-import@npm:eslint-plugin-i@latest
```

**Comment by jrnail23** [comment]
FYI, that clearly documented fix is incorrectly documented:

https://github.com/import-js/eslint-import-resolver-typescript/blob/master/README.md?plain=1#L61

> **Important when using `eslint-plugin-i` and `npm`**: Use `npm i -D eslint-plugin-import@eslint-plugin-i@latest eslint-import-resolver-typescript`, or you will end up with both `eslint-plugin-import` and `eslint-plugin-i` in your node_modules.
