### ISSUE TITLE
enhanced-resolve -> oxc-resolver

### ISSUE THREAD

**Issue by kurtextrem** [import-js/eslint-import-resolver-typescript#254]
The resolver from the [OXC project](https://github.com/oxc-project/oxc) is majorly faster: https://github.com/oxc-project/bench-nodejs-resolver/tree/main

Would you be open to a PR for this switch?

(cc @boshen, maybe you can give some insights if the module is 'ready' to be used outside of oxc)

**Comment by JounQin** [comment]
It seems it's very lack of documentation now.

**Comment by kurtextrem** [comment]
Boshen told me at least for linting purposes it's not yet ready - so closing this for now.
