### ISSUE TITLE
@types packages are resolved instead of the actual package

### ISSUE THREAD

**Issue by ahuth** [import-js/eslint-import-resolver-typescript#265]
Possibly the cause of https://github.com/import-js/eslint-plugin-import/issues/2168.

#### The issue

The `resolve` function returns the `@types/` package associated with a module, if present. This causes issues with lint rules (specifically `import/no-extraneous-dependencies`).

For example, if we have this scenario:
1. I **_don't_** have a dependency in my package.json on `uuid` (for example. It also is the same with other deps)
2. I **_do_** have `uuid` and `@types/uuid` in my node_modules as a transitive dependencies.
3. This resolver will return `node_modules/@types/uuid` as the resolved path for `uuid`
4. `import/no-extraneous-dependencies` will report that I need to install `@types/uuid`

But that's wrong! Really I need to install `uuid`

#### Why this happens

I think this code is resulting in `@types` packages being resolved when present.

https://github.com/import-js/eslint-import-resolver-typescript/blob/acaaddd73cc457a5e5a36811fede771a0ab2d5f2/src/index.ts#L194-L209

#### Possible fix

For `import/no-extraneous-dependencies`, I **_think_** `@types/` packages should never be resolved, because what we care about is that the actual package is installed, not its types. Presumably tsc will tell us if we don't have the types installed.

However, I'm not sure how the resolved paths are used by other rules.

**Comment by JounQin** [comment]
Have you tried `import/external-module-folders` setting? Which is enabled in `plugin:import/typescript`

See also https://github.com/import-js/eslint-plugin-import/blob/7a21f7e10f18c04473faadca94928af6b8e28009/config/typescript.js#L17C1-L17C1

**Comment by ahuth** [comment]
`import/external-module-folders` doesn't seem to help.

What would the effect of that on resolving `@types/foo` vs `foo` be?

**Comment by ahuth** [comment]
> import/external-module-folders helps to consider x as installed when @types/x is installed.

That's the opposite of what I'm trying to describe here.

This issue:
- `x` should **_not_** be considered installed when it's missing but `@types/x` is installed.
- Otherwise, the `import/no-extraneous-dependencies` rule tells developers to install `@types/x`, but it should be `x`.
- I think this happens because `eslint-import-resolver-typescript` always resolves `@types/x` when present

Here's a repro: https://stackblitz.com/edit/stackblitz-starters-fshhsu

**Comment by JounQin** [comment]
You didn't enable `import/external-module-folders` at all?

**Comment by ahuth** [comment]
Tried it and it didn't help (as mentioned in https://github.com/import-js/eslint-import-resolver-typescript/issues/265#issuecomment-1893783504).

I don't see how it would help. Seems like it does the opposite of what we need to resolve this issue.

**Comment by ahuth** [comment]
@JounQin https://github.com/import-js/eslint-import-resolver-typescript/issues/265#issuecomment-1894173798 has a link to a runnable reproduction in it that I posted yesterday.

**Comment by JounQin** [comment]
<img width="478" alt="image" src="https://github.com/import-js/eslint-import-resolver-typescript/assets/8336744/764d0125-f556-4af3-8ff7-586c03ef2c1b">

https://github.com/import-js/eslint-import-resolver-typescript/issues/265#issuecomment-1894870116

**Comment by ahuth** [comment]
What are you confused about? I'll try to help make it more clear or work through issues.

[index.ts](https://stackblitz.com/edit/stackblitz-starters-fshhsu?file=index.ts) has instructions how to reproduce.

**Comment by JounQin** [comment]
`import/external-module-folders` setting is not `import/no-extraneous-dependencies` rule.

**Comment by ahuth** [comment]
This isn't completed.

- The `no-extraneous-dependencies` rule is how I reproduce the issue.
- But the issue happens because `eslint-import-resolver-typescript` is resolving `@type/x` when it should be resolving `x`.

**Comment by JounQin** [comment]
@ahuth 

See also https://github.com/import-js/eslint-plugin-import/issues/1479#issuecomment-783094870
