### ISSUE TITLE
Apply to JavaScript files

### ISSUE THREAD

**Issue by magnusriga** [import-js/eslint-import-resolver-typescript#267]
The [eslint-plugin-import][1] and [eslint-import-resolver-typescript][2] docs are quite clear that the latter is needed to support tsconfig @-rules (`compilerOptions.path`).

I have set it up correctly, with these:

    settings: {
        "import/parsers": {
           "@typescript-eslint/parser": [".ts", ".tsx"]
        },
        "import/resolver": {
           typescript: {
             project,
           },
        }
    }

Where project is resolved as such:

    const project = resolve(process.cwd(), "tsconfig.json");

I know that works, it comes from [turborepo's examples][3].

The issue is when I use JavaScript files (as opposed to TypeScript). `import/no-unresolved` then throws an error.

Any way to fix this? Ideally, the typescript resolver should also be applied to the JavaScript files.

  [1]: https://github.com/import-js/eslint-plugin-import?tab=readme-ov-file#typescript
  [2]: https://github.com/import-js/eslint-import-resolver-typescript
  [3]: https://github.com/vercel/turbo/blob/main/examples/kitchen-sink/packages/config-eslint/next.js

**Comment by JounQin** [comment]
You can set `jsconfig.json` as `project`. See also #161

**Comment by magnusriga** [comment]
@JounQin Thank you. But I already have a `tsconfig.json`, which I am using in a next.js project with JavaScript files. I would like eslint import to respect the `path` setting in the `tsconfig.json`. Is that possible? TypeScript and vscode is OK with it, as I have Intellisense (autocomplete, go-to-source, etc.)

**Comment by JounQin** [comment]
Then you should add `allowJs` into `tsconfig.json`?

**Comment by magnusriga** [comment]
> Then you should add `allowJs` into `tsconfig.json`?
> 
> Or at least you should provide a minimal reproduction.

Hi,

I actually have allowJs, the setup all works as it should except for the fact that eslint throws a `import/no-undefined` when using the aliases from tsconfig in JavaScript files.

If the tsconfig was not set up correctly, I guess IntelliSense and Go to Source would not work. But it does work.

Hmmm, let me add a minimal repo shortly.

**Comment by JounQin** [comment]
> Are you saying that this import resolver (eslint-import-resolver-typescript) should work on JS files by default, when allowJs is set?

Yes.

**Comment by magnusriga** [comment]
@JounQin Minimal repo: https://github.com/magnusriga/turbo-tailwind

You can see the problem in this file (`./apps/web/src/app/foo-javascript.js`):

![image](https://github.com/import-js/eslint-import-resolver-typescript/assets/38915578/e225e44d-19ce-4e00-8492-364b5a92f899)

**Comment by JounQin** [comment]
I don't understand why it's not `@repo/typescript-config/base.json`

https://github.com/magnusriga/turbo-tailwind/blob/c368eec5cbe6ef858b2a0b36822b5e05b6ccb832/tsconfig.json#L2

**Comment by magnusriga** [comment]
@JounQin Sorry, I messed up the minimal repo. It does not show the issue. Bear with me for a few min while I recreate it.

**Comment by magnusriga** [comment]
@JounQin I was unable to recreate it. The current version of the min repo is as similar as possible to my main repo, which bizarrely started working when I restarted the devContainer.

ESLint seems a bit slow though. Did you spot anything I did in my base eslint config that should take long?

In any case, thanks a lot for the quick response, and sorry for the lack of a good reproduction.

**Comment by JounQin** [comment]
> ESLint seems a bit slow though. Did you spot anything I did in my base eslint config that should take long?

Related #176, maybe try to use relative path for `extends`.

> Any reason why it might have been necessary to restart the container? Just restarting vscode did not work.

Sorry, I'm lack of experience of dev container.
