### ISSUE TITLE
# imports throwing no-unresolved error, even though ts finds module

### ISSUE THREAD

**Issue by magnusriga** [import-js/eslint-import-resolver-typescript#270]
I am using imports in package.json, [as specified here](https://www.typescriptlang.org/docs/handbook/modules/reference.html#paths):

> Both libraries and apps can consider [package.json "imports"](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-imports-and-self-name-imports) as a standard replacement for convenience paths aliases.

Screenshot of import with eslint error:

![image](https://github.com/import-js/eslint-plugin-import/assets/38915578/bc0ad3f6-b73a-455e-97f8-1b0409210a1c)

**Screenshot of package.json:**

![image](https://github.com/import-js/eslint-plugin-import/assets/38915578/689086d9-4317-427d-ac1a-6ba0983b3a5e)

TypeScript finds the file, so no ts error is shown.

Is this just a missing feature, or is something wrong with my setup?

PS: I am using `eslint-plugin-import` and `eslint-import-resolver-typescript`, with this eslintrc (only showing important part):

```typescript
/** @type {import("eslint").Linter.Config} */
module.exports = {
  // root: true is good ESLint practice. Indicates this file is root-level eslintrc.js config used by project,
  // and ESLint should not search beyond this directory for eslintrc.js config files.
  root: true,

  // Extends shared config.
  extends: ['@nfront/eslint-config/react.js'],

  // Do not set parser here, it will override parsers from plugins

  parserOptions: {
    // MUST set project here, in project-level eslint.rc file, for eslint extension in vscode to work.
    // "project" is only used by @vercel/style-guide/eslint/typescript (@typescript/eslint/parser).
    // true: Use type information based on nearest tsconfig.json, i.e. tsconfig in same directory as this eslintrc file.
    // tsconfigRootDir: __dirname (i.e. folder of this eslintrc file): Ensures eslint command can be called from any folder,
    // and right tsconfig.json file will still be used (the one in this folder, as opposed to tsconfig from where esljnt command was run).
    project: true,
    // project: './tsconfig.json',
    tsconfigRootDir: __dirname,
    // tsconfigRootDir: import.meta.dirname,
  },

  // settings: {
    // I think these settings are MERGED with settings from config we extend.
    // 'import/resolver': {
    //   typescript: {
    //     // MUST set project here, in project-level eslint.rc file, for eslint extension in vscode to work.
    //     // "project" is only used by @vercel/style-guide/eslint/typescript (@typescript/eslint/parser).
    //     project: './tsconfig.json',
    //   },
    // },
    // 'import/external-module-folders': [
    //   'node_modules',
    //   'packages/ui',
    //   'apps/node_modules',
    // ],
  // },
};
```

**Comment by magnusriga** [comment]
@JounQin Here is a minimal repo: https://github.com/magnusriga/my-app

![image](https://github.com/import-js/eslint-import-resolver-typescript/assets/38915578/55443414-c03a-49af-83fe-c8badfc2ddea)

**Comment by magnusriga** [comment]
Ah, I found the error. `imports` needs to look like this:

```json
{
  "imports": {
    "#app/styles/*.scss": "./src/styles/scss/*.scss"
  }
}
```

Is that the recommended approach/syntax @JounQin ?

Thank you.

**Comment by JounQin** [comment]
`imports` is not supported yet, but PR welcome, I believe `enhance-resolve` already supports it.

**Comment by magnusriga** [comment]
@JounQin `imports` does work with `eslint-import-resolver-typescript`. I tried it, and no error. Check the minimal repo and apply the fix I noted above:

```
{
  "imports": {
    "#app/styles/*.scss": "./src/styles/scss/*.scss"
  }
}
```

**Comment by JounQin** [comment]
So this issue can be closed, right?

And PR welcome to add document about `imports` support, I haven never use it personally.

**Comment by magnusriga** [comment]
> So this issue can be closed, right?
> 
> And PR welcome to add document about `imports` support, I haven never use it personally.

Yes, it can be closed. Thanks for the quick replies.
