### ISSUE TITLE
Parsing error when there is a hyphen in declaration filename

### ISSUE THREAD

**Issue by adbutterfield** [import-js/eslint-import-resolver-typescript#271]
I apologize if this is the wrong repo for this issue.

I just hit something strange setting up a new project. I added a type declaration file for vitest-axe like mentioned in the [readme here](https://github.com/chaance/vitest-axe?tab=readme-ov-file#with-typescript). If I name the file `vitest-setup.d.ts` I have the error: 

`Parsing error: ESLint was configured to run on '<tsconfigRootDir>/vitest-setup.d.ts' using 'parserOptions.project': /<path to project>/packages/react/tsconfig.json
However, that TSConfig does not include this file.` 

But if I name the file `setup.d.ts` I don't have the error.

I tried to poke around a bit in eslint dependencies, but couldn't find anything. I would guess a bad regex somewhere?

**Comment by JounQin** [comment]
It's thrown from @typescript-eslint.
