### ISSUE TITLE
Remove `is-glob` dependency

### ISSUE THREAD

**Issue by benmccann** [import-js/eslint-import-resolver-typescript#331]
It was just pointed out to me that it can be replaced with `isDynamicPattern` from `tinyglobby`. I'd send a PR, but wasn't eager to fight with yarn

**Comment by SukkaW** [comment]
> I'd send a PR, but wasn't eager to fight with yarn

Do you have corepack enabled? corepack should automatically install, set up, and choose the repo's specified yarn version (`yarn@4.0.2` for the time being) for you.

**Comment by benmccann** [comment]
No, I don't have corepack installed

**Comment by SukkaW** [comment]
Do note that `eslint-import-resolver-typescript` uses `yarn@4.0.2`, so the `yarn@latest` from npm (which will be `yarn@1`) wouldn't work here.

I'd still prefer you create the PR, I myself would prefer not to "steal" your credits on this~

**Comment by benmccann** [comment]
Ah, I see. That was probably the issue then. It looks like I have yarn 1 installed.

I really don't mind you stealing credit at all. I'm not sure I really want to install corepack for such a small change to be honest. If it helps I could create the PR except for the lockfile change again, but I don't know if that saves you any effort or not
